### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by StonkGuy** [chanderlud/electrum_sweeper#1]
RUST_BACKTRACE=1 ./electrum_sweeper --delay 10 --key_file priv.txt --path /usr/local/bin/electrum                  

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', src/main.rs:115:56
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.59.0/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.59.0/library/core/src/panicking.rs:116:14
   2: core::result::unwrap_failed
             at /usr/src/rustc-1.59.0/library/core/src/result.rs:1690:5
   3: core::result::Result<T,E>::unwrap
             at /usr/src/rustc-1.59.0/library/core/src/result.rs:1018:23
   4: electrum_sweeper::main
             at ./src/main.rs:115:38
   5: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.59.0/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by StonkGuy** [comment]
Ran into another problem
RUST_BACKTRACE=1 ./electrum_sweeper --delay 10 --key_file priv.txt --path electrum -vvvvv
INFO - using electrum binary: electrum
INFO - loaded 49 private keys                                                                                                                                                                                                              
INFO - started electrum daemon                                                                                                                                                                                                             
INFO - loaded electrum wallet                                                                                                                                                                                                              
INFO - checking wallet balances                                                                                                                                                                                                            
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', src/main.rs:115:56                                                                                                   
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.59.0/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.59.0/library/core/src/panicking.rs:116:14
   2: core::result::unwrap_failed
             at /usr/src/rustc-1.59.0/library/core/src/result.rs:1690:5
   3: core::result::Result<T,E>::unwrap
             at /usr/src/rustc-1.59.0/library/core/src/result.rs:1018:23
   4: electrum_sweeper::main
             at ./src/main.rs:115:38
   5: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.59.0/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by chanderlud** [comment]
It looks like electrum is returning an unexpected value for the funded wallets command. If you can run the command yourself, you might be able to figure out whats going on.

**Comment by StonkGuy** [comment]
When I run electrum listaddresses --funded, the output is 2 square brackets []

**Comment by chanderlud** [comment]
If you look in the directory where you have been running the electrum sweeper you should see a file named sweeper_wallet. If run electrum listaddresses -w sweeper_wallet --funded you should get the same output that is crashing the sweeper.
